title: My Test blog on github !!!
author: Ishan Sarangi
email: sarangi.ishan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is just awesome. 
# social links
linkedIn: www.linkedin.com/in/ishansarangi
github_username: ishansarangi

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
